var test_stimuli = [
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -40,
    "query": 70,
    "ref1": 50,
    "ref2": 90,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 40,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -40,
    "query": 170,
    "ref1": 150,
    "ref2": 190,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 40,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -40,
    "query": 250,
    "ref1": 230,
    "ref2": 270,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 40,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -80,
    "query": 70,
    "ref1": 30,
    "ref2": 110,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -80,
    "query": 150,
    "ref1": 110,
    "ref2": 190,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -80,
    "query": 180,
    "ref1": 140,
    "ref2": 220,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -120,
    "query": 90,
    "ref1": 30,
    "ref2": 150,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 120,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -120,
    "query": 170,
    "ref1": 110,
    "ref2": 230,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 120,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -120,
    "query": 240,
    "ref1": 180,
    "ref2": 300,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 120,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -60,
    "query": 70,
    "ref1": 50,
    "ref2": 110,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -60,
    "query": 150,
    "ref1": 130,
    "ref2": 190,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -60,
    "query": 170,
    "ref1": 150,
    "ref2": 210,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -60,
    "query": 260,
    "ref1": 240,
    "ref2": 300,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -60,
    "query": 70,
    "ref1": 30,
    "ref2": 90,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -60,
    "query": 170,
    "ref1": 130,
    "ref2": 190,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -60,
    "query": 190,
    "ref1": 150,
    "ref2": 210,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -60,
    "query": 270,
    "ref1": 230,
    "ref2": 290,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -80,
    "query": 50,
    "ref1": 30,
    "ref2": 110,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -80,
    "query": 170,
    "ref1": 150,
    "ref2": 230,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -80,
    "query": 240,
    "ref1": 220,
    "ref2": 300,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -80,
    "query": 90,
    "ref1": 30,
    "ref2": 110,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -80,
    "query": 170,
    "ref1": 110,
    "ref2": 190,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -80,
    "query": 260,
    "ref1": 200,
    "ref2": 280,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -100,
    "query": 90,
    "ref1": 30,
    "ref2": 130,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -100,
    "query": 150,
    "ref1": 90,
    "ref2": 190,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -100,
    "query": 190,
    "ref1": 130,
    "ref2": 230,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -100,
    "query": 260,
    "ref1": 200,
    "ref2": 300,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -100,
    "query": 70,
    "ref1": 30,
    "ref2": 130,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -100,
    "query": 110,
    "ref1": 70,
    "ref2": 170,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -100,
    "query": 170,
    "ref1": 130,
    "ref2": 230,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -100,
    "query": 240,
    "ref1": 200,
    "ref2": 300,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -30,
    "dist_ref1_ref2": -50,
    "query": 50,
    "ref1": 30,
    "ref2": 80,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 30,
    "abs_dist_ref1_ref2": 50,
    "trial_type": "query_central"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 140,
    "dist_query_ref_2": 170,
    "dist_ref1_ref2": 30,
    "query": 220,
    "ref1": 80,
    "ref2": 50,
    "abs_dist_query_ref1": 140,
    "abs_dist_query_ref2": 170,
    "abs_dist_ref1_ref2": 30,
    "trial_type": "query_side"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -40,
    "dist_ref1_ref2": -80,
    "query": 260,
    "ref1": 220,
    "ref2": 300,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 30,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -50,
    "query": 280,
    "ref1": 250,
    "ref2": 300,
    "abs_dist_query_ref1": 30,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 50,
    "trial_type": "query_central"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -20,
    "dist_query_ref_2": 30,
    "dist_ref1_ref2": 50,
    "query": 270,
    "ref1": 290,
    "ref2": 240,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 30,
    "abs_dist_ref1_ref2": 50,
    "trial_type": "query_central"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -60,
    "dist_query_ref_2": -80,
    "dist_ref1_ref2": -20,
    "query": 210,
    "ref1": 270,
    "ref2": 290,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 80,
    "abs_dist_ref1_ref2": 20,
    "trial_type": "query_side"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -140,
    "dist_query_ref_2": -170,
    "dist_ref1_ref2": -30,
    "query": 60,
    "ref1": 200,
    "ref2": 230,
    "abs_dist_query_ref1": 140,
    "abs_dist_query_ref2": 170,
    "abs_dist_ref1_ref2": 30,
    "trial_type": "query_side"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -240,
    "dist_query_ref_2": -260,
    "dist_ref1_ref2": -20,
    "query": 40,
    "ref1": 280,
    "ref2": 300,
    "abs_dist_query_ref1": 240,
    "abs_dist_query_ref2": 260,
    "abs_dist_ref1_ref2": 20,
    "trial_type": "query_side"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -50,
    "dist_query_ref_2": -80,
    "dist_ref1_ref2": -30,
    "query": 210,
    "ref1": 260,
    "ref2": 290,
    "abs_dist_query_ref1": 50,
    "abs_dist_query_ref2": 80,
    "abs_dist_ref1_ref2": 30,
    "trial_type": "query_side"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -60,
    "dist_ref1_ref2": -120,
    "query": 100,
    "ref1": 40,
    "ref2": 160,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 120,
    "trial_type": "query_central"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 60,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -80,
    "query": 120,
    "ref1": 60,
    "ref2": 140,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -60,
    "dist_query_ref_2": -80,
    "dist_ref1_ref2": -20,
    "query": 40,
    "ref1": 100,
    "ref2": 120,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 80,
    "abs_dist_ref1_ref2": 20,
    "trial_type": "query_side"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -40,
    "query": 60,
    "ref1": 40,
    "ref2": 80,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 40,
    "trial_type": "query_central"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 40,
    "dist_query_ref_2": -30,
    "dist_ref1_ref2": -70,
    "query": 250,
    "ref1": 210,
    "ref2": 280,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 30,
    "abs_dist_ref1_ref2": 70,
    "trial_type": "query_central"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 20,
    "dist_query_ref_2": -20,
    "dist_ref1_ref2": -40,
    "query": 270,
    "ref1": 250,
    "ref2": 290,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 40,
    "trial_type": "query_central"
  }
]