var test_stimuli = [
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -40,
    "query": 70,
    "ref1": 50,
    "ref2": 90,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 40,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -40,
    "query": 170,
    "ref1": 150,
    "ref2": 190,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 40,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -40,
    "query": 250,
    "ref1": 230,
    "ref2": 270,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 40,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -80,
    "query": 70,
    "ref1": 30,
    "ref2": 110,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -80,
    "query": 140,
    "ref1": 100,
    "ref2": 180,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -80,
    "query": 180,
    "ref1": 140,
    "ref2": 220,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -80,
    "query": 260,
    "ref1": 220,
    "ref2": 300,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -120,
    "query": 90,
    "ref1": 30,
    "ref2": 150,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 120,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -120,
    "query": 170,
    "ref1": 110,
    "ref2": 230,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 120,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -120,
    "query": 240,
    "ref1": 180,
    "ref2": 300,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 120,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -60,
    "query": 70,
    "ref1": 50,
    "ref2": 110,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -60,
    "query": 150,
    "ref1": 130,
    "ref2": 190,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -60,
    "query": 170,
    "ref1": 150,
    "ref2": 210,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -60,
    "query": 260,
    "ref1": 240,
    "ref2": 300,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -60,
    "query": 70,
    "ref1": 30,
    "ref2": 90,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -60,
    "query": 170,
    "ref1": 130,
    "ref2": 190,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -60,
    "query": 190,
    "ref1": 150,
    "ref2": 210,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -60,
    "query": 270,
    "ref1": 230,
    "ref2": 290,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 60,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -80,
    "query": 50,
    "ref1": 30,
    "ref2": 110,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -80,
    "query": 160,
    "ref1": 140,
    "ref2": 220,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 20,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -80,
    "query": 240,
    "ref1": 220,
    "ref2": 300,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -80,
    "query": 90,
    "ref1": 30,
    "ref2": 110,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -80,
    "query": 180,
    "ref1": 120,
    "ref2": 200,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -20,
    "dist_ref1_ref2": -80,
    "query": 260,
    "ref1": 200,
    "ref2": 280,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 20,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -100,
    "query": 90,
    "ref1": 30,
    "ref2": 130,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -100,
    "query": 150,
    "ref1": 90,
    "ref2": 190,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -100,
    "query": 180,
    "ref1": 120,
    "ref2": 220,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 60,
    "dist_query_ref2": -40,
    "dist_ref1_ref2": -100,
    "query": 260,
    "ref1": 200,
    "ref2": 300,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 40,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -100,
    "query": 70,
    "ref1": 30,
    "ref2": 130,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -100,
    "query": 120,
    "ref1": 80,
    "ref2": 180,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -100,
    "query": 170,
    "ref1": 130,
    "ref2": 230,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "post_rik_meeting",
    "dist_query_ref1": 40,
    "dist_query_ref2": -60,
    "dist_ref1_ref2": -100,
    "query": 240,
    "ref1": 200,
    "ref2": 300,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 100,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 110,
    "dist_query_ref2": -120,
    "dist_ref1_ref2": -230,
    "query": 160,
    "ref1": 50,
    "ref2": 280,
    "abs_dist_query_ref1": 110,
    "abs_dist_query_ref2": 120,
    "abs_dist_ref1_ref2": 230,
    "trial_type": "query_central",
    "Comment": "practice"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -80,
    "dist_query_ref2": 130,
    "dist_ref1_ref2": 210,
    "query": 210,
    "ref1": 290,
    "ref2": 80,
    "abs_dist_query_ref1": 80,
    "abs_dist_query_ref2": 130,
    "abs_dist_ref1_ref2": 210,
    "trial_type": "query_central",
    "Comment": "practice"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 20,
    "dist_query_ref2": -100,
    "dist_ref1_ref2": -120,
    "query": 60,
    "ref1": 40,
    "ref2": 160,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 100,
    "abs_dist_ref1_ref2": 120,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -20,
    "dist_query_ref2": -210,
    "dist_ref1_ref2": -190,
    "query": 40,
    "ref1": 60,
    "ref2": 250,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 210,
    "abs_dist_ref1_ref2": 190,
    "trial_type": "query_side",
    "Comment": "practice"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -20,
    "dist_query_ref2": 60,
    "dist_ref1_ref2": 80,
    "query": 270,
    "ref1": 290,
    "ref2": 210,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 60,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_central",
    "Comment": "practice"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 40,
    "dist_query_ref2": 190,
    "dist_ref1_ref2": 150,
    "query": 290,
    "ref1": 250,
    "ref2": 100,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 190,
    "abs_dist_ref1_ref2": 150,
    "trial_type": "query_side",
    "Comment": "main"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -20,
    "dist_query_ref2": -100,
    "dist_ref1_ref2": -80,
    "query": 40,
    "ref1": 60,
    "ref2": 140,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 100,
    "abs_dist_ref1_ref2": 80,
    "trial_type": "query_side",
    "Comment": "main"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 40,
    "dist_query_ref2": -160,
    "dist_ref1_ref2": -200,
    "query": 120,
    "ref1": 80,
    "ref2": 280,
    "abs_dist_query_ref1": 40,
    "abs_dist_query_ref2": 160,
    "abs_dist_ref1_ref2": 200,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": 50,
    "dist_query_ref2": -150,
    "dist_ref1_ref2": -200,
    "query": 130,
    "ref1": 80,
    "ref2": 280,
    "abs_dist_query_ref1": 50,
    "abs_dist_query_ref2": 150,
    "abs_dist_ref1_ref2": 200,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -20,
    "dist_query_ref2": -230,
    "dist_ref1_ref2": -210,
    "query": 40,
    "ref1": 60,
    "ref2": 270,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 230,
    "abs_dist_ref1_ref2": 210,
    "trial_type": "query_side",
    "Comment": "main"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -20,
    "dist_query_ref2": 150,
    "dist_ref1_ref2": 170,
    "query": 250,
    "ref1": 270,
    "ref2": 100,
    "abs_dist_query_ref1": 20,
    "abs_dist_query_ref2": 150,
    "abs_dist_ref1_ref2": 170,
    "trial_type": "query_central",
    "Comment": "main"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -60,
    "dist_query_ref2": 200,
    "dist_ref1_ref2": 260,
    "query": 240,
    "ref1": 300,
    "ref2": 40,
    "abs_dist_query_ref1": 60,
    "abs_dist_query_ref2": 200,
    "abs_dist_ref1_ref2": 260,
    "trial_type": "query_central",
    "Comment": "practice"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -80,
    "dist_query_ref2": 160,
    "dist_ref1_ref2": 240,
    "query": 210,
    "ref1": 290,
    "ref2": 50,
    "abs_dist_query_ref1": 80,
    "abs_dist_query_ref2": 160,
    "abs_dist_ref1_ref2": 240,
    "trial_type": "query_central",
    "Comment": "practice"
  },
  {
    "simulation name": "balancing",
    "dist_query_ref1": -10,
    "dist_query_ref2": 150,
    "dist_ref1_ref2": 160,
    "query": 250,
    "ref1": 260,
    "ref2": 100,
    "abs_dist_query_ref1": 10,
    "abs_dist_query_ref2": 150,
    "abs_dist_ref1_ref2": 160,
    "trial_type": "query_central",
    "Comment": "main"
  }
]